export default [
  {
    id: 'dg001',
    url: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/DGart0.jpg',
    alt: 'Image 1',
    songName: 'Mayor of Simpleton',
    author: 'XTC',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/01%20-%20XTC%20-%20Mayor%20Of%20Simpleton.mp3',
    startTime: ('59'),
  },
  {
    id: 'dg002',
    url: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/DGart1.jpg',
    alt: 'Image 2',
    songName: 'Pop In My Step',
    author: 'King Gizzard & The Lizard Wizard ',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/02%20-%20King%20Gizzard%20And%20The%20Lizard%20Wizard%20-%20Pop%20In%20My%20Step.mp3',
    startTime: ('59'),
  },
  {
    id: 'dg003',
    url: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/DGart2.jpg',
    alt: 'Image 4',
    songName: 'I Believe in a Thing Called Love',
    author: 'The Darkness',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/04%20-%20The%20Darkness%20-%20I%20Believe%20in%20a%20Thing%20Called%20Love.mp3',
    startTime: ('59'),
  },
  {
    id: 'dg004',
    url: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/Dgart3.jpg',
    alt: 'Green TypeWriters (4) - The Olivia Tremor Control',
    songName: 'Green TypeWriters (4)',
    author: 'The Olivia Tremor Control',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/05%20-%20The%20Olivia%20Tremor%20Control%20-%20Green%20Typewriters.mp3',
    startTime: ('59'),
  },
  {
    id: 'dg005',
    url: "https://storage.googleapis.com/trv_test/DiscoveryGameTracks/DGart4.jpg",
    alt: 'Hey Lover - Blake Mills',
    songName: 'Hey Lover',
    author: 'Blake Mills',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/06%20-%20Blake%20Mills%20-%20Hey%20Lover.mp3',
    startTime: ('59'),
  },
  {
    id: 'dg006',
    url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',
    alt: 'Image 1',
    songName: 'temp7',
    author: 'temp',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/07%20-%20Grandaddy%20-%20Now%20Its%20On.mp3',
    startTime: ('59'),
  },
  {
    url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',
    alt: 'Image 1',
    songName: 'temp8',
    author: 'temp',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/08%20-%20Elf%20Power%20-%20Temporary%20Arm.mp3',
    startTime: ('59'),
  },
  {
    url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',
    alt: 'Image 1',
    songName: 'temp9',
    author: 'temp',
    audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/09%20-%20The%20Magnetic%20Fields%20-%20You%20and%20Me%20and%20the%20Moon.mp3',
    startTime: ('59'),
  }
]