export default [
    {
        url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',
        alt: 'Image 1',
        songName: 'temp',
        author:'temp',
        audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/01%20-%20XTC%20-%20Mayor%20Of%20Simpleton.mp3',
        startTime: ('59'),
      },
      {
          url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg2.jpg',
          alt: 'Image 2',
          songName: 'temp2',
          author:'temp',
          audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/02%20-%20King%20Gizzard%20And%20The%20Lizard%20Wizard%20-%20Pop%20In%20My%20Step.mp3',
          startTime: ('59'),
        },
        {
          url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg4.png',
          alt: 'Image 4',
          songName: 'temp4',
          author:'temp',
          audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/04%20-%20The%20Darkness%20-%20I%20Believe%20in%20a%20Thing%20Called%20Love.mp3',
          startTime: ('59'),
        },
        {
          url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',           
          alt: 'Image 1',
          songName: 'temp5',
          author:'temp',
          audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/05%20-%20The%20Olivia%20Tremor%20Control%20-%20Green%20Typewriters.mp3',
          startTime: ('59'),
        },
        {
          uurl: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',           
          alt: 'Image 1',
          songName: 'temp6',
          author:'temp',
          audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/06%20-%20Blake%20Mills%20-%20Hey%20Lover.mp3',
          startTime: ('59'),
        },
        {
          url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',
          alt: 'Image 1',
          songName: 'temp7',
          author:'temp',
          audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/07%20-%20Grandaddy%20-%20Now%20Its%20On.mp3',
          startTime: ('59'),
        },
        {
          url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',
          alt: 'Image 1',
          songName: 'temp8',
          author:'temp',
          audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/08%20-%20Elf%20Power%20-%20Temporary%20Arm.mp3',
          startTime: ('59'),
        },
        {
          url: 'https://storage.googleapis.com/trv_test/TempPlaylistImgs/tempPlaylistimg.jpg',
          alt: 'Image 1',
          songName: 'temp9',
          author:'temp',
          audio: 'https://storage.googleapis.com/trv_test/DiscoveryGameTracks/09%20-%20The%20Magnetic%20Fields%20-%20You%20and%20Me%20and%20the%20Moon.mp3',
          startTime: ('59'),
        }
]